// The following code is implicitly generated by the java program
// that executes this script.
//
// importClass(java.lang.System);
// importClass(java.util.HashMap);
// importClass(Packages.com.fc.drawings.MulledSet);
// importClass(Packages.com.fc.drawings.MulledUnit);
// var order = <<order#>>;
// var item = <<line#>>;
// var mulledSet = MulledSet.getInstance(<<order#>>);
//
// function trace(text)
// {
//	 System.out.println(text);  // write to system log
// }
//
	var drivingUnit = null;
	var alignedUnit = null;

	var cntUnits = mulledSet.getCountUnits();
	
	var n,m = 1;
	for(n=1;n <= cntUnits; n++)
	{
		drivingUnit = mulledSet.getUnit(n);
		if(drivingUnit.isLeftmostUnit())
		{
			for(;m <= cntUnits; m++)
			{
				alignedUnit = mulledSet.getUnit(m);
				if(alignedUnit.isRight(drivingUnit))
				{
					alignedUnit.horzAlignTo(drivingUnit,"BT","Center",4);
				}
			}
		}
	}

	for(n=1;n <= cntUnits; n++)
	{
		drivingUnit = mulledSet.getUnit(n);
		if(drivingUnit.isTopUnit())
		{
			for(;m <= cntUnits; m++)
			{
				alignedUnit = mulledSet.getUnit(m);
				if(alignedUnit.isBelow(drivingUnit))
				{
					alignedUnit.vertAlignTo(drivingUnit,"LR","Center",4);
				}
			}
		}
	}
	
	mulledSet.setErrorMsg("Please review and adjust grid alignment.");


 